### ISSUE TITLE
Windows: No module named slimit

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#111]
**Important:**

I can't open eXe after installing this version: https://www.dropbox.com/s/y2a572c5bcfxykx/INTEF-eXe-install-2.1.exe?dl=0

**Error:**

Traceback (most recent call last):
  File "exe", line 40, in <module>
  File "exe\application.pyc", line 35, in <module>
  File "exe\webui\webserver.pyc", line 37, in <module>
  File "exe\webui\packageredirectpage.pyc", line 29, in <module>
  File "exe\jsui\mainpage.pyc", line 48, in <module>
  File "exe\export\websiteexport.pyc", line 38, in <module>
ImportError: No module named slimit

**Comment by pedropena** [comment]
En el entorno de construcción automática no está instalada la librería y por lo tanto no se puede añadir al instalador. Lo mismo pasará con Mac.

Intentaré añadirlos para esta tarde.

**Comment by pedropena** [comment]
Los binarios de windows que se autogeneran en Dropbox ya incluyen slimit y cssmin.
