### ISSUE TITLE
Error exportación a scorm en 2.1.2 portable para Linux 

### ISSUE THREAD

**Issue by Rafav** [exelearning/iteexe#181]
Hola:

En la portable 2.1.2 en Guadalinex V9 la exportación a scorm da fallo: ERROR EN LA EXPORTACIÓN 'module' object has no attribute 'cssmin' 

La salida por terminal  es:

Welcome to eXe: the EXtremely Easy to use eLearning authoring tool
Traceback (most recent call last):
  File "/home/rafa/Descargas/2-1-2/exelib/exe/webui/webserver.py", line 177, in run
    reactor.run()
  File "/home/rafa/Descargas/2-1-2/exelib/twisted/internet/posixbase.py", line 218, in run
    self.mainLoop()
  File "/home/rafa/Descargas/2-1-2/exelib/twisted/internet/posixbase.py", line 226, in mainLoop
    self.runUntilCurrent()
  File "/home/rafa/Descargas/2-1-2/exelib/twisted/internet/base.py", line 541, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/home/rafa/Descargas/2-1-2/exelib/nevow/livepage.py", line 359, in handleInput
    self.events.publish(identifier, *(self, ) + args)
  File "/home/rafa/Descargas/2-1-2/exelib/nevow/events.py", line 43, in publish
    sub(*args)
  File "/home/rafa/Descargas/2-1-2/exelib/exe/jsui/mainpage.py", line 1003, in handleExport
    self.exportScorm(client, filename, stylesDir, "scorm1.2")
  File "/home/rafa/Descargas/2-1-2/exelib/exe/jsui/mainpage.py", line 1321, in exportScorm
    scormExport.export(self.package)
  File "/home/rafa/Descargas/2-1-2/exelib/exe/export/scormexport.py", line 520, in export
    exportMinFileCSS(listCSSFiles, outputDir)
  File "/home/rafa/Descargas/2-1-2/exelib/exe/export/helper.py", line 173, in exportMinFileCSS
    outPutFiles.write(cssmin.cssmin(files.read()))
<type 'exceptions.AttributeError'>: 'module' object has no attribute 'cssmin'

Saludos

**Comment by Rafav** [comment]
En helper.py  (exelib/exe/export ) cambiando import cssmin por
from cssmin import cssmin me ha funcionado.

Saludos
