### ISSUE TITLE
Not working at Fedora 30

### ISSUE THREAD

**Issue by AlphaX2** [exelearning/iteexe#413]
Hello,

I'm trying to use eXe on Fedora 30 and it's not working. The problem seems to be, that some of the Python modules are not available for Python2 in Fedora repos, but only for Python3.

Also the stand-alone package is not working. I get the following error message:

`$ ./exelearning.sh
Traceback (most recent call last):
  File "./exelib/exe/exe", line 36, in <module>
    from exe.application import Application
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/application.py", line 43, in <module>
    from exe.webui.webserver     import WebServer
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/webserver.py", line 37, in <module>
    from exe.webui.packageredirectpage import PackageRedirectPage
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/packageredirectpage.py", line 29, in <module>
    from exe.jsui.mainpage import MainPage
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/jsui/mainpage.py", line 47, in <module>
    from exe.webui.authoringpage     import AuthoringPage
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/authoringpage.py", line 32, in <module>
    import exe.webui.builtinblocks
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/builtinblocks.py", line 34, in <module>
    from exe.webui.galleryblock           import GalleryBlock
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/galleryblock.py", line 374, in <module>
    from exe.engine.galleryidevice  import GalleryIdevice
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/engine/galleryidevice.py", line 28, in <module>
    import Image
ImportError: No module named Image
Traceback (most recent call last):
  File "./exelib/exe/exe", line 36, in <module>
    from exe.application import Application
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/application.py", line 43, in <module>
    from exe.webui.webserver     import WebServer
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/webserver.py", line 37, in <module>
    from exe.webui.packageredirectpage import PackageRedirectPage
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/packageredirectpage.py", line 29, in <module>
    from exe.jsui.mainpage import MainPage
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/jsui/mainpage.py", line 47, in <module>
    from exe.webui.authoringpage     import AuthoringPage
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/authoringpage.py", line 32, in <module>
    import exe.webui.builtinblocks
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/builtinblocks.py", line 34, in <module>
    from exe.webui.galleryblock           import GalleryBlock
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/webui/galleryblock.py", line 374, in <module>
    from exe.engine.galleryidevice  import GalleryIdevice
  File "/home/gberkigt/Downloads/portable-intef-exe-2.3.1-linux/exelib/exe/engine/galleryidevice.py", line 28, in <module>
    import Image
ImportError: No module named Image
`
The files are there, but it seems the PIL folder is not recognised. Even with Image.py copied over to the engine folder, it's missing the i64 folder - so it seems the main folder is not added to the import paths.

**Comment by jrfern** [comment]
> Pillow 7.0.0 will be released on 2020-01-01 and will drop support for Python 2.7, making Pillow 6.x the last series to support Python 2.

https://pillow.readthedocs.io/en/stable/releasenotes/6.0.0.html#backwards-incompatible-changes

Pillow 5.X and 6.X still support python2.7. Python2.6 was dropped in 4.0.0. 

A Fedora decision? Or a dependance missing?

**Comment by JuanPerezSdweb** [comment]
Hello,

The python 2.7 end of support for  was already known to end at this year ends, and it falls within the "expected" that some distribution can be advanced a few months to this end of support.

**Comment by neurofreak-alt** [comment]
Hi!
We need to add a goal to migrate code to python3 in milestone 2.7
Distributions are actively dropping packages with python2 from their repositories.
Snap is not the solution. It itself has a large number of bugs.
So we need to figure out how much code and which components to port and have at least a list of it.

**Comment by ignaciogros** [comment]
Hi,
They're already working on a new version, written in PHP. It'll probably be "eXeLearning 3.0".
There won't be big changes in eXe 2.x unless there are new contributions.
