### ISSUE TITLE
Can't run the Snap package after updating Xubuntu

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#559]
Traceback (most recent call last):
   File "/snap/exelearning/6/bin/exe", line 40, in <module>
     from exe.application import Application
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/application.py",
line 37, in <module>
     from exe.webui.webserver     import WebServer
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/webserver.py",
line 37, in <module>
     from exe.webui.packageredirectpage import PackageRedirectPage
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/packageredirectpage.py",
line 29, in <module>
     from exe.jsui.mainpage import MainPage
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/jsui/mainpage.py",
line 47, in <module>
     from exe.webui.authoringpage     import AuthoringPage
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/authoringpage.py",
line 32, in <module>
     import exe.webui.builtinblocks
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/builtinblocks.py",
line 50, in <module>
     from exe.webui.sortblock import SortBlockInc
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/sortblock.py",
line 19, in <module>
     from exe.export.exportmediaconverter import ExportMediaConverter
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/export/exportmediaconverter.py",
line 9, in <module>
     from exe.engine.package          import Package
   File
"/snap/exelearning/6/lib/python2.7/site-packages/exe/engine/package.py",
line 35, in <module>
     from dateutil.tz import tzlocal
ImportError: cannot import name tzlocal

**Comment by ignaciogros** [comment]
**This is important.** We have to check the Snap package configuration.

Thank you for all these tests and information, @xavipuigc:

**Trying to install the Snap package in Ubuntu 18.04.5 LTS:**

> Traceback (most recent call last):
>   File "/snap/exelearning/6/bin/exe", line 40, in <module>
>     from exe.application import Application
>   File "/snap/exelearning/6/lib/python2.7/site-packages/exe/application.py", line 37, in <module>
>     from exe.webui.webserver     import WebServer
>   File "/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/webserver.py", line 37, in <module>
>     from exe.webui.packageredirectpage import PackageRedirectPage
>   File "/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/packageredirectpage.py", line 29, in <module>
>     from exe.jsui.mainpage import MainPage
>   File "/snap/exelearning/6/lib/python2.7/site-packages/exe/jsui/mainpage.py", line 41, in <module>
>     from exe.jsui.idevicepane        import IdevicePane
>   File "/snap/exelearning/6/lib/python2.7/site-packages/exe/jsui/idevicepane.py", line 30, in <module>
>     from exe.engine.jsidevice import JsIdevice;
>   File "/snap/exelearning/6/lib/python2.7/site-packages/exe/engine/jsidevice.py", line 27, in <module>
>     from exe.engine.field                               import Field, TextField, TextAreaField, FeedbackField
>   File "/snap/exelearning/6/lib/python2.7/site-packages/exe/engine/field.py", line 36, in <module>
>     from exe.webui                import common
>   File "/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/common.py", line 36, in <module>
>     from bs4                       import BeautifulSoup
> ImportError: cannot import name BeautifulSoup

**Trying to install a new Snap package (master branch) in Ubuntu 18.04.5 LTS:**

> Traceback (most recent call last):
>   File "/snap/exelearning/x1/bin/exe", line 40, in <module>
>     from exe.application import Application
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/application.py", line 37, in <module>
>     from exe.webui.webserver     import WebServer
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/webui/webserver.py", line 37, in <module>
>     from exe.webui.packageredirectpage import PackageRedirectPage
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/webui/packageredirectpage.py", line 29, in <module>
>     from exe.jsui.mainpage import MainPage
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/jsui/mainpage.py", line 47, in <module>
>     from exe.webui.authoringpage     import AuthoringPage
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/webui/authoringpage.py", line 32, in <module>
>     import exe.webui.builtinblocks
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/webui/builtinblocks.py", line 34, in <module>
>     from exe.webui.galleryblock           import GalleryBlock
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/webui/galleryblock.py", line 369, in <module>
>     from exe.engine.galleryidevice  import GalleryIdevice
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/engine/galleryidevice.py", line 30, in <module>
>     from PIL import Image, ImageDraw
>   File "/home/xavi/.local/lib/python2.7/site-packages/PIL/Image.py", line 63, in <module>
>     from PIL import _imaging as core
> ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory

**The Snap libraries are not in the snapcraft.yaml_template:**

> PYTHONPATH: $SNAP/lib:$SNAP/usr/lib/:$SNAP/lib/python2.7/site-packages/usr/share/exe/:$PYTHONPATH

**We add "$SNAP/lib/python2.7/site-packages" to PYTHONPATH:**

> PYTHONPATH: $SNAP/lib:$SNAP/usr/lib/:$SNAP/lib/python2.7/site-packages:$SNAP/lib/python2.7/site-packages/usr/share/exe/:$PYTHONPATH

**We get this error:**

> Traceback (most recent call last):
>   File "/snap/exelearning/x1/bin/exe", line 58, in <module>
>     main()
>   File "/snap/exelearning/x1/bin/exe", line 55, in main
>     application.main()
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/application.py", line 109, in main
>     self.loadConfiguration()
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/application.py", line 237, in loadConfiguration
>     self.config = configKlass()
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/engine/config.py", line 271, in __init__
>     self._writeDefaultConfigFile()
>   File "/snap/exelearning/x1/lib/python2.7/site-packages/exe/engine/config.py", line 301, in _writeDefaultConfigFile
>     defaultVal = getattr(self, optionName)
> AttributeError: 'SnapConfig' object has no attribute 'eXeUIversion'

**Temporally solved adding "self.eXeUIversion= 2" to the "_overrideDefaultVals" function in "exe/engine/snapconfig.py".**

And it works!

But unless you create a new Snap package, I think that **you'll have to wait until eXe 2.6 is released**. Sorry...
