### ISSUE TITLE
Problem after updating snapd?

### ISSUE THREAD

**Issue by ignaciogros** [exelearning/iteexe#563]
A user reports that after upgrading snapd from 2.48.2 to 2.49 (he's using Debian Testing), exe won't launch. I have snapd 2.49 in Ubuntu 20.04 and it works fine. Does it work for you?

He gets this messages:

```
/snap/bin/exelearning 
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Traceback (most recent call last):
  File "/snap/exelearning/6/bin/exe", line 40, in <module>
    from exe.application import Application
  File "/snap/exelearning/6/lib/python2.7/site-packages/exe/application.py", line 37, in <module>
    from exe.webui.webserver     import WebServer
  File "/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/webserver.py", line 37, in <module>
    from exe.webui.packageredirectpage import PackageRedirectPage
  File "/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/packageredirectpage.py", line 29, in <module>
    from exe.jsui.mainpage import MainPage
  File "/snap/exelearning/6/lib/python2.7/site-packages/exe/jsui/mainpage.py", line 47, in <module>
    from exe.webui.authoringpage     import AuthoringPage
  File "/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/authoringpage.py", line 32, in <module>
    import exe.webui.builtinblocks
  File "/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/builtinblocks.py", line 26, in <module>
    from exe.webui.jsblock                import JsBlock
  File "/snap/exelearning/6/lib/python2.7/site-packages/exe/webui/jsblock.py", line 19, in <module>
    from webassets.utils import common_path_prefix
ImportError: No module named utils
```

**Comment by ignaciogros** [comment]
@xavipuigc: This might be related to #559

**Comment by ignaciogros** [comment]
I think that @xavipuigc's revision fixes this.
