### ISSUE TITLE
Snap not working on ArchLinux

### ISSUE THREAD

**Issue by rolodoom** [exelearning/iteexe#601]
I just tested eXeLearning on ArchLinux and it's not working. 

Sytem:
ArchLinux kernel 5.10.78-1-lts
bash 5.1.8
KDE 5.87.0 / Plasma 5.23.2

Here is the terminal content when executing eXeLearning:

```bash
Traceback (most recent call last):
  File "/snap/exelearning/9/bin/exe", line 40, in <module>
    from exe.application import Application
  File "/snap/exelearning/9/lib/python2.7/site-packages/exe/application.py", line 37, in <module>
    from exe.webui.webserver     import WebServer
  File "/snap/exelearning/9/lib/python2.7/site-packages/exe/webui/webserver.py", line 37, in <module>
    from exe.webui.packageredirectpage import PackageRedirectPage
  File "/snap/exelearning/9/lib/python2.7/site-packages/exe/webui/packageredirectpage.py", line 28, in <module>
    from exe.webui.renderable     import RenderableResource
  File "/snap/exelearning/9/lib/python2.7/site-packages/exe/webui/renderable.py", line 36, in <module>
    from nevow import loaders
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/nevow/__init__.py", line 153, in <module>
    load(basic_adapters)
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/nevow/__init__.py", line 41, in load
    compy.registerAdapter(a, clean(o), i)
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/nevow/compyCompat.py", line 49, in registerAdapter
    adapterFactory = namedAny(adapterFactory)
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/nevow/compyCompat.py", line 34, in namedAny
    return _namedAny(name)
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/twisted/python/reflect.py", line 352, in namedAny
    topLevelPackage = __import__(trialname)
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/formless/webform.py", line 33, in <module>
    from nevow.static import File
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/nevow/static.py", line 138, in <module>
    class File:
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/nevow/static.py", line 158, in File
    contentTypes = loadMimeTypes()
  File "/snap/exelearning/9/lib/python2.7/site-packages/usr/share/exe/nevow/static.py", line 123, in loadMimeTypes
    contentTypes.update(mimetypes.read_mime_types(location))
  File "/snap/exelearning/9/usr/lib/python2.7/mimetypes.py", line 373, in read_mime_types
    db = MimeTypes()
  File "/snap/exelearning/9/usr/lib/python2.7/mimetypes.py", line 66, in __init__
    init()
  File "/snap/exelearning/9/usr/lib/python2.7/mimetypes.py", line 358, in init
    db.read(file)
  File "/snap/exelearning/9/usr/lib/python2.7/mimetypes.py", line 202, in read
    with open(filename) as fp:
IOError: [Errno 13] Permission denied: '/etc/httpd/conf/mime.types'
```

**Comment by Javiobcn** [comment]
Hello, the snap works correctly using last version of ArchLinux:

uname -r (Kernel)
5.15.5-arch1-1 (64-bit)

bash --version
5.1.12 (1) -release (x86-64-pc-linux-gnu)

KDE Plasma
5.23.3

KDE Frameworks
5.88.0

Graphic platform
Wayland

I have checked that in the SNAP package downloaded from snap store MimeTeX is not working. # 599 as described in the issue.

I have installed a new snap file with the corrections in 34edb0fbc03cd7122bf10d58592215724eecff1b and then the Mimetex worked as expected.
